name = "stacks-auth"
main = "src/index.ts"
compatibility_date = "2024-09-23"

[vars]
WORKER_BASE_URL = "https://stacks-auth.stacks-f04.workers.dev"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "0b2e5b5e503e4febb12f2942e4d4c3fb"
